### PR TITLE
Fix 32 bit df on 64 bit Fedora and warn others.

### PR DESCRIPTION
**Pull request by miffedmap**
There's a common issue on 64 bit distros where df fails with errors similar to `cannot load "data/art/foo.png"` because ld loads the 64bit version of libz required by libpng rather then the 32 bit version.
This fixes the problem on fedora and emits a warning on other distros (since I haven't tested others).

### CODE REVIEW

**Comment by lethosor** [comment]
It would be nice to move that to another file so it can be easily used by the `dfhack` script as well.

**Comment by miffedmap** [comment]
Yeah, I'm just tracing that out. I think I'll need to get a PR into dfhack first. hold off for now, this can be solved more cleanly.

**Comment by miffedmap** [comment]
https://github.com/DFHack/dfhack/pull/505

**Comment by miffedmap** [comment]
DFHack PR is waiting but it looks like it might take some time until they respond. No sense in waiting since the dfhack script will require modification each time anyway to setup the proper env variables.
- Broke out the checks into a seperate `distro_fixes.sh`
- Which both df/dfhack scripts now source before running
- And the patch to dfhack is included as a seperate commit which when/if it gets merged upstream will no longer be needed.

These scripts are fairly static upstream so although you'll need to apply the commits that
modify df/dfhack whenever df/dfhack are upgraded, it should be just a simple cherry-pick to apply them.

If there are further comments lets hear them but I think this can be merged. 
Fedora is fairly popular and it'd be nice for LNP to work out of the box on it.

**Comment by miffedmap** [comment]
bump.

**Comment by BeauBouchard** [comment]
@lethosor  the portion from DFHack/dfhack#505, Has this been added to DFhack dev?

**Comment by lethosor** [comment]
Merged in dfhack/dfhack#508. I believe that's part of DFHack 0.40.24-r2.

**Comment by BeauBouchard** [comment]
:D Thanks @miffedmap !!

I will be testing these changes, and thank you for contributing to the project :D :D :+1:

**Comment by miffedmap** [comment]
:+1:

**Comment by miffedmap** [comment]
This could obsolete the `gentoopatch` utility, just needs some minor tweaks by a gentoo user.

**Pull request merged**
