### PR TITLE
Add gentoo support to distro_fixes.sh

### LINKED ISSUE #23: distro_fixes.sh should support gentoo
`distro_fixes.sh` takes care of distro-specific adjustments in order to run df, specifically
a known issue when running df (which is 32 bit) on 64 bit distros having to do with libz which manifests 
as bogus "file not found" errors. 
fedora support is already there, but gentoo support isn't yet.
https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues/1#issuecomment-76594113.

@ald0n, let's take care of required changes to `distro_fixes.sh` here. also, are you comfortable with bash scripts and git/github, if so can you make a pull-request with the required changes to `distro_fixes.sh`, the comments there should be all you need. 
if not, can you tell me what is the path for the default install of the 32bit version of `libz.so.1` on gentoo?

### PR DESCRIPTION
**Pull request by miffedmap**
@ald0n, can you see check if this is enough to get df working from the command line?

closes #23

### CODE REVIEW

**Comment by ald0n** [comment]
with new _distro_fixes.sh_ i got
**./df** or **./dfhack**

> [distro_fixes.sh] you must provide DF_DIR as an argument.

I also changed paths in df

> PRELOAD_LIB="/lib32/libz.so.1 ./hack/libdfhack.so"

and in dfhack

> PRELOAD_LIB="/lib32/libz.so.1:./hack/libdfhack.so"

This working with previous distro_fixes.sh

**Comment by miffedmap** [comment]
@BeauBouchard call me cautious, but I was waiting to get an ok from @ald0n before asking you to merge. I'll flag the PR as WIP next time.

**Comment by BeauBouchard** [comment]
@miffedmap Sorry, I was waiting so i could fetch the changes. Also thank you for all your help of late.

**Comment by ald0n** [comment]
In all versions of _distro_fixes.sh_ i got the same

> [distro_fixes.sh] you must provide DF_DIR as an argument.

How can i set it?

**Comment by miffedmap** [comment]
glad to help, it's nice to work on a small project and just help make stuff work for people.

@ald0n, to avoid git, you can just replace the `df`/`dfhack` scripts with the updated versions from git master:
- [df](https://raw.githubusercontent.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/master/pack/df_linux/df)  download link.
- [dfhack](https://raw.githubusercontent.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/master/pack/df_linux/dfhack) download link.

**Comment by ald0n** [comment]
ok, here we go again :D
when i set path to libz.so.1 **manually** as i said above here https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/pull/24#issuecomment-76602431 it works fine.
when i use a newer file _distro_fixes.sh_ from your commits i got this

> [distro_fixes.sh] you must provide DF_DIR as an argument.

**Comment by miffedmap** [comment]
you're running `df` though, right? you're not supposed to run `distro_fixes.sh` directly.
if so, can you paste the contents of `df` here?

if all files are up to date, you run `df` which calls  `distro_fixes.sh` . That sets some variables, which `df` then uses when running the actual game.

**Comment by ald0n** [comment]
yep, just df, not distro_fixes.sh

> #!/bin/sh
> DF_DIR=$(dirname "$0")
> cd "${DF_DIR}"
> export SDL_DISABLE_LOCK_KEYS=1 # Work around for bug in Debian/Ubuntu SDL patch.
> #export SDL_VIDEO_CENTERED=1 # Centre the screen.  Messes up resizing.
> 
> `#` >>> LNP modification:
> 
> #apply any ARC/distro fixes
> source "$DF_DIR/distro_fixes.sh"
> LD_PRELOAD="/lib32/libz.so.1" ./libs/Dwarf_Fortress "$@" # Go, go, go! :)
> exit $?
> 
> `#` <<< LNP modification:
> 
> ./libs/Dwarf_Fortress "$@" # Go, go, go! :)

**Comment by miffedmap** [comment]
that's not the up to date version of `df` , look at the link i provided. the line should read

```
source "./distro_fixes.sh" "${DF_DIR}"
```

and you've hardcoded LD_PRELOAD which means we can't tell if the fix in #24 works or not...
maybe we should just drop this, we're not making much progress.

**Comment by ald0n** [comment]
My bad. Now it works with latest @BeauBouchard merge of _distro_fixes.sh_
But still no success with startlnp/PyLNP https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues/1

**Comment by miffedmap** [comment]
ok, well that's something anyway.

**Pull request merged**
