### PR TITLE
Making repo more minimal

### PR DESCRIPTION
**Pull request by BeauBouchard**
Removed all binaries,

Removed all files in the graphics folder. If you need to compile the package, install graphics from [Fircy's DFgraphics](https://github.com/Lazy-Newb-Pack/DFgraphics).

### CODE REVIEW

**Comment by miffedmap** [comment]
Hey @BeauBouchard,

The repo history still weighs in at 120MB, you might consider renaming this repo to -backup and restarting as a new repo with a fresh snapshot (preemptive :-1: on `git-filter-branch` if needed).

Trashing history once wouldn't be that terrible, not much "dev" going on here.

**Comment by lethosor** [comment]
What's wrong with `git filter-branch`? I'd like to keep at least some history, if possible.

**Comment by miffedmap** [comment]
`git filter-branch` actively destroys history and in fact corrupts history by creating commits where README's reference files that no longer exist and zsh/dash-scripts that reference missing paths which have since been renamed...

The ban on rewriting public history is about 2 things: immutability and collaboration. And while you  can't avoid invalidating forks and pulls, you can keep the integrity of past history by simply moving it as-is to a legacy repo.

**Comment by miffedmap** [comment]
:+1:

I noticed now that the new repo has no releases and both the readme and website point at R2 .
Less high-maintenance to have everything point at the GH releases page (once you tag a release)

**Comment by lethosor** [comment]
I put up stubs for the current releases that link to the old repo. I'm not sure how many links pointing to old releases are still floating around, but I'm not aware of an easy way to transfer all releases (including binaries) to this repo.

**Pull request merged**
